#!/bin/bash

# this shell script runs the main python script which contains all the coding logic

PYTHON_INTERPRETER=$(which python3)

SCRIPT_DIR=$(dirname "$0")
DIR_PATH=$(realpath "$SCRIPT_DIR")
PYTHON_FILE_PATH="$DIR_PATH/main.py"

$PYTHON_INTERPRETER "$PYTHON_FILE_PATH"